//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_MixingPlant_Device
    {
        public int Id { get; set; }
        public string DeviceFacId { get; set; }
        public string Name { get; set; }
        public string DeviceCode { get; set; }
        public string PlatformName { get; set; }
        public string ProjectName { get; set; }
        public string BiaoDuanName { get; set; }
        public string ProjectCode { get; set; }
        public string Factorycode { get; set; }
        public string Memo { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
        public string ShowName { get; set; }
    }
}
