//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ZhangLa_CurrentMonitor
    {
        public int Id { get; set; }
        public string DotId { get; set; }
        public Nullable<int> DeviceNo { get; set; }
        public Nullable<int> ConnState { get; set; }
        public string ZLState { get; set; }
        public string KongEx { get; set; }
        public string LiangType { get; set; }
        public string liangstr { get; set; }
        public Nullable<decimal> Per100Press { get; set; }
        public Nullable<int> InitPress { get; set; }
        public string Gang1State { get; set; }
        public string Gang2State { get; set; }
        public string Gang3State { get; set; }
        public string Gang4State { get; set; }
        public Nullable<decimal> Gang1Press { get; set; }
        public Nullable<decimal> Gang2Press { get; set; }
        public Nullable<decimal> Gang3Press { get; set; }
        public Nullable<decimal> Gang4Press { get; set; }
        public Nullable<decimal> Gang1Extend { get; set; }
        public Nullable<decimal> Gang2Extend { get; set; }
        public Nullable<decimal> Gang3Extend { get; set; }
        public Nullable<decimal> Gang4Extend { get; set; }
    }
}
