//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_MixingPlant_228RoadYBPeiHeBi
    {
        public int ID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Prop_No { get; set; }
        public string Strength { get; set; }
        public string NAM_GL1 { get; set; }
        public Nullable<int> BPB_GL1 { get; set; }
        public string NAM_GL2 { get; set; }
        public Nullable<int> BPB_GL2 { get; set; }
        public string NAM_GL3 { get; set; }
        public Nullable<int> BPB_GL3 { get; set; }
        public string NAM_FLA1 { get; set; }
        public Nullable<int> BPB_FLA1 { get; set; }
        public string NAM_FLA2 { get; set; }
        public Nullable<int> BPB_FLA2 { get; set; }
        public string NAM_FLA3 { get; set; }
        public Nullable<int> BPB_FLA3 { get; set; }
        public string NAM_WJA1 { get; set; }
        public Nullable<double> BPB_WJA1 { get; set; }
        public string NAM_WJA2 { get; set; }
        public Nullable<int> BPB_WJA2 { get; set; }
        public string NAM_Shui1 { get; set; }
        public Nullable<double> BPB_Shui1 { get; set; }
        public string NAM_Shui2 { get; set; }
        public Nullable<double> BPB_Shui2 { get; set; }
        public Nullable<int> MixTime1 { get; set; }
    }
}
