//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_MixingPlant_Material
    {
        public Tb_MixingPlant_Material()
        {
            this.Tb_MixingPlant_Dosage = new HashSet<Tb_MixingPlant_Dosage>();
            this.Tb_MixingPlant_RecipeList = new HashSet<Tb_MixingPlant_RecipeList>();
        }
    
        public string Id { get; set; }
        public string DeviceFacId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public Nullable<decimal> PError { get; set; }
    
        public virtual ICollection<Tb_MixingPlant_Dosage> Tb_MixingPlant_Dosage { get; set; }
        public virtual ICollection<Tb_MixingPlant_RecipeList> Tb_MixingPlant_RecipeList { get; set; }
    }
}
