//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_LZTSBLab_SNKYResult
    {
        public string ZuHao { get; set; }
        public string LingQI { get; set; }
        public string PingZhong { get; set; }
        public string OneKN { get; set; }
        public int ShunXu { get; set; }
        public string LenAv { get; set; }
        public string WidAv { get; set; }
        public string CurveData { get; set; }
    }
}
