//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_MixingPlant_tScsjAll
    {
        public int xh { get; set; }
        public System.DateTime rdate { get; set; }
        public Nullable<int> orderID { get; set; }
        public string orderName { get; set; }
        public Nullable<int> formuID { get; set; }
        public string formuName { get; set; }
        public string slump { get; set; }
        public string intensityGrade { get; set; }
        public string humidity { get; set; }
        public Nullable<double> accumulativeTotal { get; set; }
        public Nullable<double> per { get; set; }
        public string Client { get; set; }
        public string Site { get; set; }
        public string Operator { get; set; }
        public string CarNo { get; set; }
        public string Part { get; set; }
        public string Driver { get; set; }
        public string operateMode { get; set; }
        public Nullable<short> flag { get; set; }
    }
}
