//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_MixingPlant_tScsjAllBody
    {
        public int rd { get; set; }
        public System.DateTime rdate { get; set; }
        public Nullable<int> xh { get; set; }
        public Nullable<int> pc { get; set; }
        public Nullable<int> gc { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public string material { get; set; }
        public Nullable<double> goal { get; set; }
        public Nullable<double> fact { get; set; }
        public Nullable<double> margin { get; set; }
        public Nullable<short> flag { get; set; }
    }
}
