//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_YaJiang_Curve
    {
        public int Id { get; set; }
        public Nullable<int> DeviceNo { get; set; }
        public string DotId { get; set; }
        public Nullable<int> Kong { get; set; }
        public string KongEx { get; set; }
        public string Liang { get; set; }
        public Nullable<int> IDmx { get; set; }
        public string DataAry { get; set; }
    
        public virtual Tb_YaJiang_Data Tb_YaJiang_Data { get; set; }
    }
}
