//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_LZT_WL_SB_MixingPlant_Dosage
    {
        public int ID { get; set; }
        public int Piece { get; set; }
        public Nullable<int> MaterID { get; set; }
        public string Material { get; set; }
        public Nullable<decimal> WatFull { get; set; }
        public Nullable<decimal> RecAmnt { get; set; }
        public Nullable<decimal> PlanAmnt { get; set; }
        public Nullable<decimal> FactAmnt { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
    }
}
