//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_LZT_WL_SB_MixingPlant_Produce
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Customer { get; set; }
        public string ProjName { get; set; }
        public string ConsPos { get; set; }
        public Nullable<int> PieCnt { get; set; }
        public string BetLev { get; set; }
        public Nullable<int> MixLast { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public Nullable<int> Vehicle { get; set; }
        public string Driver { get; set; }
    }
}
