//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_LZTLab_SNKYResult
    {
        public int TestSerialNo { get; set; }
        public int MPaIndex { get; set; }
        public string MPa { get; set; }
        public string KN { get; set; }
        public string TestDate { get; set; }
        public string TestTime { get; set; }
        public string CurveData { get; set; }
    }
}
