//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_LZTSBLab_SNKYParm
    {
        public string ZuHao { get; set; }
        public string PingZhong { get; set; }
        public string LingQi { get; set; }
        public string GuiGe { get; set; }
        public string Speed { get; set; }
        public Nullable<int> GroNum { get; set; }
        public Nullable<int> LoadType { get; set; }
        public Nullable<int> YanShi { get; set; }
        public Nullable<int> SelectGroNum { get; set; }
        public string ShuiNiBiaoHao { get; set; }
        public string JianLi { get; set; }
        public string HeTongHao { get; set; }
        public string WeiTuiDanWei { get; set; }
        public string XianChangZhuangHao { get; set; }
        public string ShiYanDanWei { get; set; }
    }
}
