//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_MixingPlant_228RoadYB
    {
        public int ID { get; set; }
        public System.DateTime ScTime { get; set; }
        public Nullable<double> Output_vol { get; set; }
        public string NAM_GL1 { get; set; }
        public Nullable<int> MBZ_GL1 { get; set; }
        public Nullable<int> CLZ_GL1 { get; set; }
        public string NAM_GL2 { get; set; }
        public Nullable<int> MBZ_GL2 { get; set; }
        public Nullable<int> CLZ_GL2 { get; set; }
        public string NAM_GL3 { get; set; }
        public Nullable<int> MBZ_GL3 { get; set; }
        public Nullable<int> CLZ_GL3 { get; set; }
        public string NAM_FLA2 { get; set; }
        public Nullable<int> MBZ_FLA2 { get; set; }
        public Nullable<int> CLZ_FLA2 { get; set; }
        public string NAM_WJA1 { get; set; }
        public Nullable<double> MBZ_WJA1 { get; set; }
        public Nullable<double> CLZ_WJA1 { get; set; }
        public Nullable<int> JDZ_WJC4 { get; set; }
        public string NAM_Shui1 { get; set; }
        public Nullable<double> MBZ_Shui1 { get; set; }
        public Nullable<double> CLZ_Shui1 { get; set; }
        public string Job_No { get; set; }
        public string Prop_No { get; set; }
        public string Cust_Nm { get; set; }
        public string Proj_Nm { get; set; }
        public string Location { get; set; }
        public string Site_No { get; set; }
        public string Contr_No { get; set; }
        public string Strength { get; set; }
        public string Const_Unit { get; set; }
        public string NAM_FLA3 { get; set; }
        public Nullable<int> MBZ_FLA3 { get; set; }
        public Nullable<int> CLZ_FLA3 { get; set; }
        public string NAM_WJA2 { get; set; }
        public Nullable<int> MBZ_WJA2 { get; set; }
        public Nullable<int> CLZ_WJA2 { get; set; }
        public string NAM_Shui2 { get; set; }
        public Nullable<double> MBZ_Shui2 { get; set; }
        public Nullable<double> CLZ_Shui2 { get; set; }
        public string NAM_FLA1 { get; set; }
        public Nullable<int> MBZ_FLA1 { get; set; }
        public Nullable<int> CLZ_FLA1 { get; set; }
    }
}
