//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envionment_Data
    {
        public int Id { get; set; }
        public string DeviceCode { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Humidity { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Envionment_ProjectInfo Envionment_ProjectInfo { get; set; }
    }
}
