//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gyxp_Stat
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string PileSite { get; set; }
        public string DeviceCode { get; set; }
        public Nullable<double> Luo { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public Nullable<double> TotalFlow { get; set; }
        public Nullable<double> TotalDust { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
    }
}
