//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YuHuan_TrafficConstructionMISEntities : DbContext
    {
        public YuHuan_TrafficConstructionMISEntities()
            : base("name=YuHuan_TrafficConstructionMISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Gyxp> Gyxps { get; set; }
        public DbSet<Gyxp_Stat> Gyxp_Stat { get; set; }
        public DbSet<Tb_Lab_Department> Tb_Lab_Department { get; set; }
        public DbSet<Tb_Lab_ProjectName> Tb_Lab_ProjectName { get; set; }
        public DbSet<Tb_Lab_Test> Tb_Lab_Test { get; set; }
        public DbSet<Tb_Lab_TestItem> Tb_Lab_TestItem { get; set; }
        public DbSet<Tb_Login> Tb_Login { get; set; }
        public DbSet<Tb_Main_Menu> Tb_Main_Menu { get; set; }
        public DbSet<Tb_MixingPlant_Dosage> Tb_MixingPlant_Dosage { get; set; }
        public DbSet<Tb_MixingPlant_Material> Tb_MixingPlant_Material { get; set; }
        public DbSet<Tb_MixingPlant_Piece> Tb_MixingPlant_Piece { get; set; }
        public DbSet<Tb_MixingPlant_Produce> Tb_MixingPlant_Produce { get; set; }
        public DbSet<Tb_MixingPlant_Recipe> Tb_MixingPlant_Recipe { get; set; }
        public DbSet<Tb_MixingPlant_RecipeList> Tb_MixingPlant_RecipeList { get; set; }
        public DbSet<Tb_YaJiang_CurrentMonitor> Tb_YaJiang_CurrentMonitor { get; set; }
        public DbSet<Tb_YaJiang_Curve> Tb_YaJiang_Curve { get; set; }
        public DbSet<Tb_YaJiang_Data> Tb_YaJiang_Data { get; set; }
        public DbSet<Tb_YaJiang_ProjectInfo> Tb_YaJiang_ProjectInfo { get; set; }
        public DbSet<Tb_ZhangLa_CurrentMonitor> Tb_ZhangLa_CurrentMonitor { get; set; }
        public DbSet<Tb_ZhangLa_Curve> Tb_ZhangLa_Curve { get; set; }
        public DbSet<Tb_ZhangLa_Data> Tb_ZhangLa_Data { get; set; }
        public DbSet<Tb_ZhangLa_ProjectInfo> Tb_ZhangLa_ProjectInfo { get; set; }
        public DbSet<Envionment_Data> Envionment_Data { get; set; }
        public DbSet<Envionment_DeviceProject> Envionment_DeviceProject { get; set; }
        public DbSet<Envionment_ProjectInfo> Envionment_ProjectInfo { get; set; }
        public DbSet<Tb_MixingPlant_Device> Tb_MixingPlant_Device { get; set; }
        public DbSet<Tb_YaJiang_Project> Tb_YaJiang_Project { get; set; }
        public DbSet<Tb_ZhangLa_Project> Tb_ZhangLa_Project { get; set; }
        public DbSet<Tb_Flow_Page> Tb_Flow_Page { get; set; }
        public DbSet<Tb_Flow_Statistics> Tb_Flow_Statistics { get; set; }
        public DbSet<Tb_Flow_Visit> Tb_Flow_Visit { get; set; }
        public DbSet<Access_Lab_GJLS> Access_Lab_GJLS { get; set; }
        public DbSet<Access_Lab_GJLSParm> Access_Lab_GJLSParm { get; set; }
        public DbSet<Access_Lab_GJLSResult> Access_Lab_GJLSResult { get; set; }
        public DbSet<Access_Lab_HNTKY> Access_Lab_HNTKY { get; set; }
        public DbSet<Access_Lab_HNTKYParm> Access_Lab_HNTKYParm { get; set; }
        public DbSet<Access_Lab_HNTKYResult> Access_Lab_HNTKYResult { get; set; }
        public DbSet<Access_Lab_SNKY> Access_Lab_SNKY { get; set; }
        public DbSet<Access_Lab_SNKYParm> Access_Lab_SNKYParm { get; set; }
        public DbSet<Access_Lab_SNKYResult> Access_Lab_SNKYResult { get; set; }
        public DbSet<Access_Lab_SNKZ> Access_Lab_SNKZ { get; set; }
        public DbSet<Access_Lab_SNKZParm> Access_Lab_SNKZParm { get; set; }
        public DbSet<Access_Lab_SNKZResult> Access_Lab_SNKZResult { get; set; }
        public DbSet<Access_LZT_WL_SB_MixingPlant> Access_LZT_WL_SB_MixingPlant { get; set; }
        public DbSet<Access_LZT_WL_SB_MixingPlant_Dosage> Access_LZT_WL_SB_MixingPlant_Dosage { get; set; }
        public DbSet<Access_LZT_WL_SB_MixingPlant_Piece> Access_LZT_WL_SB_MixingPlant_Piece { get; set; }
        public DbSet<Access_LZT_WL_SB_MixingPlant_Produce> Access_LZT_WL_SB_MixingPlant_Produce { get; set; }
        public DbSet<Access_LZTEBLab_SNKY> Access_LZTEBLab_SNKY { get; set; }
        public DbSet<Access_LZTEBLab_SNKYParm> Access_LZTEBLab_SNKYParm { get; set; }
        public DbSet<Access_LZTEBLab_SNKYResult> Access_LZTEBLab_SNKYResult { get; set; }
        public DbSet<Access_LZTEBLab_SNKZ> Access_LZTEBLab_SNKZ { get; set; }
        public DbSet<Access_LZTEBLab_SNKZParm> Access_LZTEBLab_SNKZParm { get; set; }
        public DbSet<Access_LZTEBLab_SNKZResult> Access_LZTEBLab_SNKZResult { get; set; }
        public DbSet<Access_LZTJL2Lab_SNKY> Access_LZTJL2Lab_SNKY { get; set; }
        public DbSet<Access_LZTJL2Lab_SNKYParm> Access_LZTJL2Lab_SNKYParm { get; set; }
        public DbSet<Access_LZTJL2Lab_SNKYResult> Access_LZTJL2Lab_SNKYResult { get; set; }
        public DbSet<Access_LZTJL2Lab_SNKZ> Access_LZTJL2Lab_SNKZ { get; set; }
        public DbSet<Access_LZTJL2Lab_SNKZParm> Access_LZTJL2Lab_SNKZParm { get; set; }
        public DbSet<Access_LZTJL2Lab_SNKZResult> Access_LZTJL2Lab_SNKZResult { get; set; }
        public DbSet<Access_LZTLab_SNKY> Access_LZTLab_SNKY { get; set; }
        public DbSet<Access_LZTLab_SNKYResult> Access_LZTLab_SNKYResult { get; set; }
        public DbSet<Access_LZTLab_SNKZ> Access_LZTLab_SNKZ { get; set; }
        public DbSet<Access_LZTLab_SNKZResult> Access_LZTLab_SNKZResult { get; set; }
        public DbSet<Access_LZTSBLab_SNKY> Access_LZTSBLab_SNKY { get; set; }
        public DbSet<Access_LZTSBLab_SNKYParm> Access_LZTSBLab_SNKYParm { get; set; }
        public DbSet<Access_LZTSBLab_SNKYResult> Access_LZTSBLab_SNKYResult { get; set; }
        public DbSet<Access_LZTSBLab_SNKZ> Access_LZTSBLab_SNKZ { get; set; }
        public DbSet<Access_LZTSBLab_SNKZParm> Access_LZTSBLab_SNKZParm { get; set; }
        public DbSet<Access_LZTSBLab_SNKZResult> Access_LZTSBLab_SNKZResult { get; set; }
        public DbSet<Access_LZTSDBLab_SNKY> Access_LZTSDBLab_SNKY { get; set; }
        public DbSet<Access_LZTSDBLab_SNKYParm> Access_LZTSDBLab_SNKYParm { get; set; }
        public DbSet<Access_LZTSDBLab_SNKYResult> Access_LZTSDBLab_SNKYResult { get; set; }
        public DbSet<Access_LZTSDBLab_SNKZ> Access_LZTSDBLab_SNKZ { get; set; }
        public DbSet<Access_LZTSDBLab_SNKZParm> Access_LZTSDBLab_SNKZParm { get; set; }
        public DbSet<Access_LZTSDBLab_SNKZResult> Access_LZTSDBLab_SNKZResult { get; set; }
        public DbSet<Access_LZTYBLab_SNKY> Access_LZTYBLab_SNKY { get; set; }
        public DbSet<Access_LZTYBLab_SNKYParm> Access_LZTYBLab_SNKYParm { get; set; }
        public DbSet<Access_LZTYBLab_SNKYResult> Access_LZTYBLab_SNKYResult { get; set; }
        public DbSet<Access_LZTYBLab_SNKZ> Access_LZTYBLab_SNKZ { get; set; }
        public DbSet<Access_LZTYBLab_SNKZParm> Access_LZTYBLab_SNKZParm { get; set; }
        public DbSet<Access_LZTYBLab_SNKZResult> Access_LZTYBLab_SNKZResult { get; set; }
        public DbSet<Access_MixingPlant_228RoadYB> Access_MixingPlant_228RoadYB { get; set; }
        public DbSet<Access_MixingPlant_228RoadYBPeiHeBi> Access_MixingPlant_228RoadYBPeiHeBi { get; set; }
        public DbSet<Access_MixingPlant_Intensity> Access_MixingPlant_Intensity { get; set; }
        public DbSet<Access_MixingPlant_Parm> Access_MixingPlant_Parm { get; set; }
        public DbSet<Access_MixingPlant_Parm2> Access_MixingPlant_Parm2 { get; set; }
        public DbSet<Access_MixingPlant_tScsjAll> Access_MixingPlant_tScsjAll { get; set; }
        public DbSet<Access_MixingPlant_tScsjAll2> Access_MixingPlant_tScsjAll2 { get; set; }
        public DbSet<Access_MixingPlant_tScsjAllBody> Access_MixingPlant_tScsjAllBody { get; set; }
        public DbSet<Access_MixingPlant_tScsjAllBody2> Access_MixingPlant_tScsjAllBody2 { get; set; }
        public DbSet<Sdf_LZT_SD_MixingPlant> Sdf_LZT_SD_MixingPlant { get; set; }
        public DbSet<Sdf_LZT_SD_MixingPlant_2> Sdf_LZT_SD_MixingPlant_2 { get; set; }
        public DbSet<Service_Config> Service_Config { get; set; }
        public DbSet<Service_Status> Service_Status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tb_ZhangLa1_Curve> Tb_ZhangLa1_Curve { get; set; }
        public DbSet<Tb_ZhangLa1_Data> Tb_ZhangLa1_Data { get; set; }
        public DbSet<Tb_ZhangLa1_Device> Tb_ZhangLa1_Device { get; set; }
        public DbSet<Tb_ZhangLa1_Project> Tb_ZhangLa1_Project { get; set; }
        public DbSet<Tb_YaJiang1_Curve> Tb_YaJiang1_Curve { get; set; }
        public DbSet<Tb_YaJiang1_Data> Tb_YaJiang1_Data { get; set; }
        public DbSet<Tb_YaJiang1_Device> Tb_YaJiang1_Device { get; set; }
        public DbSet<Tb_YaJiang1_Project> Tb_YaJiang1_Project { get; set; }
        public DbSet<Tb_Lab_Curve> Tb_Lab_Curve { get; set; }
        public DbSet<Tb_Lab_Type> Tb_Lab_Type { get; set; }
        public DbSet<Yanghu_SourceData> Yanghu_SourceData { get; set; }
        public DbSet<Yanghu_StatData> Yanghu_StatData { get; set; }
    }
}
