//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sdf_LZT_SD_MixingPlant
    {
        public string 任务单号 { get; set; }
        public string 砼标号 { get; set; }
        public string 操作员 { get; set; }
        public string 客户名称 { get; set; }
        public string 工程名称 { get; set; }
        public string 施工部位 { get; set; }
        public string 本次方量 { get; set; }
        public string 调水量 { get; set; }
        public string 运输车号 { get; set; }
        public System.DateTime 本次时间 { get; set; }
        public string 骨料一配方值 { get; set; }
        public string 骨料一当前值 { get; set; }
        public string 骨料一实际值 { get; set; }
        public string 骨料一含水率 { get; set; }
        public string 骨料二配方值 { get; set; }
        public string 骨料二当前值 { get; set; }
        public string 骨料二实际值 { get; set; }
        public string 骨料二含水率 { get; set; }
        public string 骨料三配方值 { get; set; }
        public string 骨料三当前值 { get; set; }
        public string 骨料三实际值 { get; set; }
        public string 骨料三含水率 { get; set; }
        public string 骨料四配方值 { get; set; }
        public string 骨料四当前值 { get; set; }
        public string 骨料四实际值 { get; set; }
        public string 骨料四含水率 { get; set; }
        public string 水泥一配方值 { get; set; }
        public string 水泥一当前值 { get; set; }
        public string 水泥一实际值 { get; set; }
        public string 水泥二配方值 { get; set; }
        public string 水泥二当前值 { get; set; }
        public string 水泥二实际值 { get; set; }
        public string 水泥三配方值 { get; set; }
        public string 水泥三当前值 { get; set; }
        public string 水泥三实际值 { get; set; }
        public string 粉煤灰一配方值 { get; set; }
        public string 粉煤灰一当前值 { get; set; }
        public string 粉煤灰一实际值 { get; set; }
        public string 粉煤灰二配方值 { get; set; }
        public string 粉煤灰二当前值 { get; set; }
        public string 粉煤灰二实际值 { get; set; }
        public string 水配方值 { get; set; }
        public string 水当前值 { get; set; }
        public string 水实际值 { get; set; }
        public string 附加剂配方值 { get; set; }
        public string 附加剂当前值 { get; set; }
        public string 附加剂实际值 { get; set; }
        public string 添加剂一配方值 { get; set; }
        public string 添加剂一当前值 { get; set; }
        public string 添加剂一实际值 { get; set; }
        public string 添加剂二配方值 { get; set; }
        public string 添加剂二当前值 { get; set; }
        public string 添加剂二实际值 { get; set; }
        public string 施工地址 { get; set; }
        public string 塌落度 { get; set; }
        public string 搅拌时间 { get; set; }
    }
}
