//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Config
    {
        public int Id { get; set; }
        public string ServiceName { get; set; }
        public string ServiceAddress { get; set; }
        public string ServiceDesc { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public Nullable<int> ScanTime { get; set; }
        public Nullable<int> IsMoniter { get; set; }
        public Nullable<int> ErrorHandler { get; set; }
    }
}
