//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Flow_Page
    {
        public Tb_Flow_Page()
        {
            this.Tb_Flow_Statistics = new HashSet<Tb_Flow_Statistics>();
            this.Tb_Flow_Visit = new HashSet<Tb_Flow_Visit>();
        }
    
        public int Id { get; set; }
        public string PageName { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<Tb_Flow_Statistics> Tb_Flow_Statistics { get; set; }
        public virtual ICollection<Tb_Flow_Visit> Tb_Flow_Visit { get; set; }
    }
}
