//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Lab_Curve
    {
        public int Id { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Datas { get; set; }
    
        public virtual Tb_Lab_Test Tb_Lab_Test { get; set; }
        public virtual Tb_Lab_Type Tb_Lab_Type { get; set; }
    }
}
