//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Lab_Test
    {
        public Tb_Lab_Test()
        {
            this.Tb_Lab_TestItem = new HashSet<Tb_Lab_TestItem>();
            this.Tb_Lab_Curve = new HashSet<Tb_Lab_Curve>();
        }
    
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public int TestItemId { get; set; }
        public string TestNo { get; set; }
        public string TestUser { get; set; }
        public string TestDevice { get; set; }
        public int ReworkCount { get; set; }
        public Nullable<System.DateTime> TestTime { get; set; }
        public string TestResult { get; set; }
    
        public virtual Tb_Lab_Department Tb_Lab_Department { get; set; }
        public virtual Tb_Lab_ProjectName Tb_Lab_ProjectName { get; set; }
        public virtual ICollection<Tb_Lab_TestItem> Tb_Lab_TestItem { get; set; }
        public virtual ICollection<Tb_Lab_Curve> Tb_Lab_Curve { get; set; }
    }
}
