//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Lab_Department
    {
        public Tb_Lab_Department()
        {
            this.Tb_Lab_Test = new HashSet<Tb_Lab_Test>();
        }
    
        public int Id { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentCode { get; set; }
        public string PlatformName { get; set; }
        public string ProjectName { get; set; }
        public string BiaoDuanName { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    
        public virtual ICollection<Tb_Lab_Test> Tb_Lab_Test { get; set; }
    }
}
