//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Lab_Type
    {
        public Tb_Lab_Type()
        {
            this.Tb_Lab_Curve = new HashSet<Tb_Lab_Curve>();
        }
    
        public int Id { get; set; }
        public string CurveName { get; set; }
    
        public virtual ICollection<Tb_Lab_Curve> Tb_Lab_Curve { get; set; }
    }
}
