//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_MixingPlant_Piece
    {
        public Tb_MixingPlant_Piece()
        {
            this.Tb_MixingPlant_Dosage = new HashSet<Tb_MixingPlant_Dosage>();
        }
    
        public string Id { get; set; }
        public string DeviceFacId { get; set; }
        public string BhzId { get; set; }
        public string ProduceId { get; set; }
        public string Serial { get; set; }
        public Nullable<System.DateTime> DatTim { get; set; }
        public Nullable<System.DateTime> BldTimStart { get; set; }
        public Nullable<System.DateTime> BldTimEnd { get; set; }
        public Nullable<int> BldTim { get; set; }
        public Nullable<decimal> PieAmnt { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public Nullable<int> DosageClass { get; set; }
    
        public virtual ICollection<Tb_MixingPlant_Dosage> Tb_MixingPlant_Dosage { get; set; }
        public virtual Tb_MixingPlant_Produce Tb_MixingPlant_Produce { get; set; }
    }
}
