//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_MixingPlant_Recipe
    {
        public Tb_MixingPlant_Recipe()
        {
            this.Tb_MixingPlant_Produce = new HashSet<Tb_MixingPlant_Produce>();
            this.Tb_MixingPlant_RecipeList = new HashSet<Tb_MixingPlant_RecipeList>();
        }
    
        public string Id { get; set; }
        public string DeviceFacId { get; set; }
        public string Code { get; set; }
        public string BetLev { get; set; }
        public Nullable<System.DateTime> DatTim { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
    
        public virtual ICollection<Tb_MixingPlant_Produce> Tb_MixingPlant_Produce { get; set; }
        public virtual ICollection<Tb_MixingPlant_RecipeList> Tb_MixingPlant_RecipeList { get; set; }
    }
}
