//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_YaJiang_Data
    {
        public Tb_YaJiang_Data()
        {
            this.Tb_YaJiang_Curve = new HashSet<Tb_YaJiang_Curve>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DeviceNo { get; set; }
        public string LiangType { get; set; }
        public string LiangStr { get; set; }
        public string KongEx { get; set; }
        public string DotId { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public Nullable<System.DateTime> ZLTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ZLNum { get; set; }
        public Nullable<int> Kong { get; set; }
        public string ZLType { get; set; }
        public Nullable<int> IType { get; set; }
        public Nullable<int> CycleTime { get; set; }
        public Nullable<decimal> ShuiQ { get; set; }
        public Nullable<decimal> ShuiNiQ { get; set; }
        public Nullable<decimal> AdditiveQ { get; set; }
        public Nullable<decimal> PressSX { get; set; }
        public Nullable<decimal> PressXX { get; set; }
        public Nullable<int> Keeptime { get; set; }
        public Nullable<decimal> ZhenKongPree { get; set; }
        public Nullable<decimal> TotalSize { get; set; }
        public Nullable<decimal> EntrPree { get; set; }
        public Nullable<decimal> ExitPree { get; set; }
        public Nullable<decimal> EntrAvgSpeed { get; set; }
        public Nullable<decimal> ExitMaxSpeed { get; set; }
        public Nullable<int> JiaoBanTime { get; set; }
        public Nullable<decimal> ShuiRatio { get; set; }
        public Nullable<int> JiangWendu { get; set; }
        public Nullable<int> HJWendu { get; set; }
        public Nullable<decimal> LLShuiQ { get; set; }
        public Nullable<decimal> LLShuiNiQ { get; set; }
        public Nullable<decimal> LLAdditiveQ { get; set; }
        public string Pass { get; set; }
        public string MaojiangQK { get; set; }
        public string ZJFangXiang { get; set; }
        public string JiangSize { get; set; }
        public string LiaoSize { get; set; }
        public string ShuiSize { get; set; }
        public string LLSize { get; set; }
    
        public virtual ICollection<Tb_YaJiang_Curve> Tb_YaJiang_Curve { get; set; }
        public virtual Tb_YaJiang_ProjectInfo Tb_YaJiang_ProjectInfo { get; set; }
    }
}
