//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_YaJiang_ProjectInfo
    {
        public Tb_YaJiang_ProjectInfo()
        {
            this.Tb_YaJiang_Data = new HashSet<Tb_YaJiang_Data>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DeviceNo { get; set; }
        public string DotId { get; set; }
        public string ProjectName { get; set; }
        public string ShiGong { get; set; }
        public string JianLi { get; set; }
        public string HunNingTu { get; set; }
        public string ZiJianYiJian { get; set; }
        public string JianLiYiJian { get; set; }
        public string JianLiRen { get; set; }
        public string JiShuYuan { get; set; }
        public string ZhiJianRen { get; set; }
        public string SubProject { get; set; }
        public string ZJLiaoName { get; set; }
        public string ZJFangXiang { get; set; }
        public Nullable<decimal> ZJIniSpeed { get; set; }
        public string JiangWendu { get; set; }
        public string HJWendu { get; set; }
        public Nullable<System.DateTime> ZLDatetime { get; set; }
        public string SuHuaJiL { get; set; }
        public string PengHuaJiL { get; set; }
        public string ShuiNiYL { get; set; }
        public string QinShuiLv { get; set; }
        public string JiLuRen { get; set; }
        public string ZBJiShuYuan { get; set; }
        public string ShuiWendu { get; set; }
        public string JiangSize { get; set; }
        public string LiaoSize { get; set; }
        public Nullable<decimal> ShuiSize { get; set; }
        public Nullable<decimal> ShuiNiMD { get; set; }
        public Nullable<decimal> AdditiveMD { get; set; }
        public string LLSize { get; set; }
        public string TotalSize { get; set; }
        public string AdditiveXH { get; set; }
        public string BengXH { get; set; }
        public string ZhuangNo { get; set; }
    
        public virtual ICollection<Tb_YaJiang_Data> Tb_YaJiang_Data { get; set; }
    }
}
