//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_YaJiang1_Project
    {
        public Tb_YaJiang1_Project()
        {
            this.Tb_YaJiang1_Device = new HashSet<Tb_YaJiang1_Device>();
        }
    
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string DotName { get; set; }
    
        public virtual ICollection<Tb_YaJiang1_Device> Tb_YaJiang1_Device { get; set; }
    }
}
