//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ZhangLa1_Data
    {
        public Tb_ZhangLa1_Data()
        {
            this.Tb_ZhangLa1_Curve = new HashSet<Tb_ZhangLa1_Curve>();
        }
    
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public string LiangType { get; set; }
        public string LiangNo { get; set; }
        public string KongNo { get; set; }
        public Nullable<int> ZhangLaCount { get; set; }
        public string ZLType { get; set; }
        public Nullable<int> KongCount { get; set; }
        public Nullable<decimal> Per100Kn { get; set; }
        public Nullable<decimal> InitKn { get; set; }
        public Nullable<decimal> Extend { get; set; }
        public Nullable<decimal> RealExtend { get; set; }
        public Nullable<decimal> ExtendError { get; set; }
        public Nullable<int> BaoYaTime { get; set; }
        public Nullable<decimal> HuiSuo { get; set; }
        public Nullable<System.DateTime> ZLDate { get; set; }
        public Nullable<decimal> Per10Kn1 { get; set; }
        public Nullable<decimal> Per20Kn1 { get; set; }
        public Nullable<decimal> Per50Kn1 { get; set; }
        public Nullable<decimal> Per100Kn1 { get; set; }
        public Nullable<decimal> Extend1 { get; set; }
        public Nullable<decimal> RealExtend1 { get; set; }
        public Nullable<int> Gang1Flag { get; set; }
        public Nullable<decimal> Per10Kn2 { get; set; }
        public Nullable<decimal> Per20Kn2 { get; set; }
        public Nullable<decimal> Per50Kn2 { get; set; }
        public Nullable<decimal> Per100Kn2 { get; set; }
        public Nullable<decimal> Extend2 { get; set; }
        public Nullable<decimal> RealExtend2 { get; set; }
        public Nullable<int> Gang2Flag { get; set; }
        public Nullable<decimal> Per10Kn3 { get; set; }
        public Nullable<decimal> Per20Kn3 { get; set; }
        public Nullable<decimal> Per50Kn3 { get; set; }
        public Nullable<decimal> Per100Kn3 { get; set; }
        public Nullable<decimal> Extend3 { get; set; }
        public Nullable<decimal> RealExtend3 { get; set; }
        public Nullable<int> Gang3Flag { get; set; }
        public Nullable<decimal> Per10Kn4 { get; set; }
        public Nullable<decimal> Per20Kn4 { get; set; }
        public Nullable<decimal> Per50Kn4 { get; set; }
        public Nullable<decimal> Per100Kn4 { get; set; }
        public Nullable<decimal> Extend4 { get; set; }
        public Nullable<decimal> RealExtend4 { get; set; }
        public Nullable<int> Gang4Flag { get; set; }
        public Nullable<decimal> ExtendError1 { get; set; }
        public Nullable<decimal> ExtendError2 { get; set; }
        public Nullable<decimal> ExtendError3 { get; set; }
        public Nullable<decimal> ExtendError4 { get; set; }
        public Nullable<decimal> Per10Extend1 { get; set; }
        public Nullable<decimal> Per20Extend1 { get; set; }
        public Nullable<decimal> Per50Extend1 { get; set; }
        public Nullable<decimal> Per100Extend1 { get; set; }
        public Nullable<decimal> Per10Extend2 { get; set; }
        public Nullable<decimal> Per20Extend2 { get; set; }
        public Nullable<decimal> Per50Extend2 { get; set; }
        public Nullable<decimal> Per100Extend2 { get; set; }
        public Nullable<decimal> Per10Extend3 { get; set; }
        public Nullable<decimal> Per20Extend3 { get; set; }
        public Nullable<decimal> Per50Extend3 { get; set; }
        public Nullable<decimal> Per100Extend3 { get; set; }
        public Nullable<decimal> Per10Extend4 { get; set; }
        public Nullable<decimal> Per20Extend4 { get; set; }
        public Nullable<decimal> Per50Extend4 { get; set; }
        public Nullable<decimal> Per100Extend4 { get; set; }
        public Nullable<decimal> JiaPianHuiSuo { get; set; }
        public Nullable<decimal> DingHuiSuo { get; set; }
    
        public virtual ICollection<Tb_ZhangLa1_Curve> Tb_ZhangLa1_Curve { get; set; }
        public virtual Tb_ZhangLa1_Device Tb_ZhangLa1_Device { get; set; }
    }
}
