//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ZhangLa1_Curve
    {
        public int Id { get; set; }
        public Nullable<int> ZLDataId { get; set; }
        public Nullable<decimal> Gang1Kn { get; set; }
        public Nullable<decimal> Gang1Extend { get; set; }
        public Nullable<decimal> Gang2Kn { get; set; }
        public Nullable<decimal> Gang2Extend { get; set; }
        public Nullable<decimal> Gang3Kn { get; set; }
        public Nullable<decimal> Gang3Extend { get; set; }
        public Nullable<decimal> Gang4Kn { get; set; }
        public Nullable<decimal> Gang4Extend { get; set; }
        public Nullable<System.DateTime> CurveTime { get; set; }
    
        public virtual Tb_ZhangLa1_Data Tb_ZhangLa1_Data { get; set; }
    }
}
