//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ZhangLa_Data
    {
        public Tb_ZhangLa_Data()
        {
            this.Tb_ZhangLa_Curve = new HashSet<Tb_ZhangLa_Curve>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DeviceNo { get; set; }
        public string LiangType { get; set; }
        public string LiangStr { get; set; }
        public Nullable<int> KongNo { get; set; }
        public string KongEx { get; set; }
        public Nullable<int> ZhangLaCount { get; set; }
        public string DotId { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public Nullable<System.DateTime> ZLTime { get; set; }
        public string ZLType { get; set; }
        public Nullable<int> DanShu { get; set; }
        public Nullable<int> ZLNum { get; set; }
        public Nullable<int> Kong { get; set; }
        public Nullable<decimal> Per100Press { get; set; }
        public Nullable<int> InitPress { get; set; }
        public Nullable<decimal> Extend { get; set; }
        public Nullable<decimal> Elasticity { get; set; }
        public Nullable<decimal> Per10Extend1 { get; set; }
        public Nullable<decimal> Per10Mpa1 { get; set; }
        public Nullable<decimal> Per20Extend1 { get; set; }
        public Nullable<decimal> Per20Mpa1 { get; set; }
        public Nullable<decimal> Per50Extend1 { get; set; }
        public Nullable<decimal> Per50Mpa1 { get; set; }
        public Nullable<decimal> Per100Extend1 { get; set; }
        public Nullable<decimal> Per100Mpa1 { get; set; }
        public Nullable<decimal> FixedExtend1 { get; set; }
        public Nullable<decimal> RealExtend1 { get; set; }
        public Nullable<decimal> Per10Extend2 { get; set; }
        public Nullable<decimal> Per10Mpa2 { get; set; }
        public Nullable<decimal> Per20Extend2 { get; set; }
        public Nullable<decimal> Per20Mpa2 { get; set; }
        public Nullable<decimal> Per50Extend2 { get; set; }
        public Nullable<decimal> Per50Mpa2 { get; set; }
        public Nullable<decimal> Per100Extend2 { get; set; }
        public Nullable<decimal> Per100Mpa2 { get; set; }
        public Nullable<decimal> FixedExtend2 { get; set; }
        public Nullable<decimal> RealExtend2 { get; set; }
        public Nullable<decimal> Per10Extend3 { get; set; }
        public Nullable<decimal> Per10Mpa3 { get; set; }
        public Nullable<decimal> Per20Extend3 { get; set; }
        public Nullable<decimal> Per20Mpa3 { get; set; }
        public Nullable<decimal> Per50Extend3 { get; set; }
        public Nullable<decimal> Per50Mpa3 { get; set; }
        public Nullable<decimal> Per100Extend3 { get; set; }
        public Nullable<decimal> Per100Mpa3 { get; set; }
        public Nullable<decimal> FixedExtend3 { get; set; }
        public Nullable<decimal> RealExtend3 { get; set; }
        public Nullable<decimal> Per10Extend4 { get; set; }
        public Nullable<decimal> Per10Mpa4 { get; set; }
        public Nullable<decimal> Per20Extend4 { get; set; }
        public Nullable<decimal> Per20Mpa4 { get; set; }
        public Nullable<decimal> Per50Extend4 { get; set; }
        public Nullable<decimal> Per50Mpa4 { get; set; }
        public Nullable<decimal> Per100Extend4 { get; set; }
        public Nullable<decimal> Per100Mpa4 { get; set; }
        public Nullable<decimal> FixedExtend4 { get; set; }
        public Nullable<decimal> RealExtend4 { get; set; }
        public Nullable<decimal> Extend2 { get; set; }
        public Nullable<decimal> Elasticity2 { get; set; }
        public Nullable<decimal> Extend3 { get; set; }
        public Nullable<decimal> Elasticity3 { get; set; }
        public Nullable<decimal> Extend4 { get; set; }
        public Nullable<decimal> Elasticity4 { get; set; }
        public Nullable<int> HuiSuoL { get; set; }
        public Nullable<decimal> ExtendError1 { get; set; }
        public Nullable<decimal> ExtendError2 { get; set; }
        public Nullable<decimal> ExtendError3 { get; set; }
        public Nullable<decimal> ExtendError4 { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> ChaoZhFlag { get; set; }
        public Nullable<int> ChaoZhPer { get; set; }
        public Nullable<decimal> ChaoZhExtend1 { get; set; }
        public Nullable<decimal> ChaoZhMpa1 { get; set; }
        public Nullable<decimal> ChaoZhExtend2 { get; set; }
        public Nullable<decimal> ChaoZhMpa2 { get; set; }
        public Nullable<decimal> ChaoZhExtend3 { get; set; }
        public Nullable<decimal> ChaoZhMpa3 { get; set; }
        public Nullable<decimal> ChaoZhExtend4 { get; set; }
        public Nullable<decimal> ChaoZhMpa4 { get; set; }
        public Nullable<int> BaoYaTime1 { get; set; }
        public Nullable<int> BaoYaTime2 { get; set; }
        public Nullable<int> BaoYaTime3 { get; set; }
        public Nullable<int> BaoYaTime4 { get; set; }
        public Nullable<decimal> Per10JiaPian1 { get; set; }
        public Nullable<decimal> Per20JiaPian1 { get; set; }
        public Nullable<decimal> Per50JiaPian1 { get; set; }
        public Nullable<decimal> Per100JiaPian1 { get; set; }
        public Nullable<decimal> Per10JiaPian2 { get; set; }
        public Nullable<decimal> Per20JiaPian2 { get; set; }
        public Nullable<decimal> Per50JiaPian2 { get; set; }
        public Nullable<decimal> Per100JiaPian2 { get; set; }
        public Nullable<decimal> Per10JiaPian3 { get; set; }
        public Nullable<decimal> Per20JiaPian3 { get; set; }
        public Nullable<decimal> Per50JiaPian3 { get; set; }
        public Nullable<decimal> Per100JiaPian3 { get; set; }
        public Nullable<decimal> Per10JiaPian4 { get; set; }
        public Nullable<decimal> Per20JiaPian4 { get; set; }
        public Nullable<decimal> Per50JiaPian4 { get; set; }
        public Nullable<decimal> Per100JiaPian4 { get; set; }
        public Nullable<decimal> ZHMianJi1 { get; set; }
        public Nullable<decimal> ZHMoZu1 { get; set; }
        public Nullable<decimal> ZHMianJi2 { get; set; }
        public Nullable<decimal> ZHMoZu2 { get; set; }
        public Nullable<decimal> ZHMianJi3 { get; set; }
        public Nullable<decimal> ZHMoZu3 { get; set; }
        public Nullable<decimal> ZHMianJi4 { get; set; }
        public Nullable<decimal> ZHMoZu4 { get; set; }
        public Nullable<decimal> WorkLen { get; set; }
        public Nullable<int> Gang1Flag { get; set; }
        public Nullable<int> Gang2Flag { get; set; }
        public Nullable<int> Gang3Flag { get; set; }
        public Nullable<int> Gang4Flag { get; set; }
    
        public virtual ICollection<Tb_ZhangLa_Curve> Tb_ZhangLa_Curve { get; set; }
        public virtual Tb_ZhangLa_ProjectInfo Tb_ZhangLa_ProjectInfo { get; set; }
    }
}
