//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_YaJiang1_Device
    {
        public Tb_YaJiang1_Device()
        {
            this.Tb_YaJiang1_Data = new HashSet<Tb_YaJiang1_Data>();
        }
    
        public string Id { get; set; }
        public Nullable<int> DeviceNo { get; set; }
        public string UnitType { get; set; }
        public string Vender { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceCode { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    
        public virtual ICollection<Tb_YaJiang1_Data> Tb_YaJiang1_Data { get; set; }
        public virtual Tb_YaJiang1_Project Tb_YaJiang1_Project { get; set; }
    }
}
