//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_LZTLab_SNKZ
    {
        public int SerialNO { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string TestTime { get; set; }
        public string MPaRes { get; set; }
        public string KNRes { get; set; }
        public string TestNo { get; set; }
        public string SampleKind { get; set; }
        public string StrengthGrid { get; set; }
        public string SampleSize { get; set; }
        public string SpanLength { get; set; }
        public string SampleAge { get; set; }
        public string Speed { get; set; }
        public string IntervalTime { get; set; }
        public string UserName { get; set; }
        public string ExpFacility { get; set; }
    }
}
