//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ZhangLa_ProjectInfo
    {
        public Tb_ZhangLa_ProjectInfo()
        {
            this.Tb_ZhangLa_Data = new HashSet<Tb_ZhangLa_Data>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DeviceNo { get; set; }
        public string DotId { get; set; }
        public string ShiGong { get; set; }
        public string JianLi { get; set; }
        public string ProjectName { get; set; }
        public string HunNingTu { get; set; }
        public string GangJiaoXian { get; set; }
        public string ZhangLaStyle { get; set; }
        public Nullable<System.DateTime> JiaoZhuDate { get; set; }
        public string YouBiao { get; set; }
        public string QianJinDing { get; set; }
        public string JianLiYiJian { get; set; }
        public string ZLFuZeRen { get; set; }
        public string JianCe { get; set; }
        public string JSFuZeRen { get; set; }
        public string JiLu { get; set; }
        public string FuHe { get; set; }
        public string SubProject { get; set; }
        public string GouJianNo { get; set; }
        public string ZLBH { get; set; }
        public Nullable<decimal> liangLen { get; set; }
        public Nullable<int> KongDaoNum { get; set; }
        public string DeviceVender { get; set; }
        public string DeviceZhuBH { get; set; }
        public string DeviceFuBH { get; set; }
        public Nullable<System.DateTime> BiaoDingRQ { get; set; }
        public string QianJinDing1 { get; set; }
        public string QianJinDing2 { get; set; }
        public string BiaoDingRQ1 { get; set; }
        public string BiaoDingRQ2 { get; set; }
        public Nullable<int> ShiYongCS1 { get; set; }
        public Nullable<int> ShiYongCS2 { get; set; }
        public string GangJiaoXianJh { get; set; }
        public string GangJiaoXianQD { get; set; }
        public string GangJiaoXianZJ { get; set; }
        public string GangJiaoXianTX { get; set; }
        public string YuZhiLiangChang { get; set; }
        public string ShiKuaiBH { get; set; }
        public string ShiKuaiQD { get; set; }
        public string ZhangLaQD { get; set; }
        public string GJXKZYL { get; set; }
        public string HJWendu { get; set; }
        public string MaoVender { get; set; }
        public string MaoXH { get; set; }
        public string QiGongdu { get; set; }
        public string HuaSiQK { get; set; }
        public string ChuLiQK { get; set; }
        public string ZhuangNo { get; set; }
        public string GJLIngQi { get; set; }
        public string DuanSiLv { get; set; }
    
        public virtual ICollection<Tb_ZhangLa_Data> Tb_ZhangLa_Data { get; set; }
    }
}
