//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_LZTEBLab_SNKY
    {
        public string ZuHao { get; set; }
        public string LingQi { get; set; }
        public Nullable<int> GroNum { get; set; }
        public string PingZhong { get; set; }
        public string Speed { get; set; }
        public string GroKN { get; set; }
        public string GroMPa { get; set; }
        public string ExpMan { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string ExpCop { get; set; }
        public Nullable<int> SelectGroNum { get; set; }
        public string ExpFacility { get; set; }
    }
}
