//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_Lab_GJLSParm
    {
        public int Id { get; set; }
        public string GroupID { get; set; }
        public string TestID { get; set; }
        public string ParamName { get; set; }
        public string ParamValue { get; set; }
    }
}
