//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_MixingPlant_Parm2
    {
        public int rd { get; set; }
        public System.DateTime rdate { get; set; }
        public Nullable<int> xh { get; set; }
        public Nullable<int> pc { get; set; }
        public int gc { get; set; }
        public Nullable<int> idParm { get; set; }
        public string parm { get; set; }
        public Nullable<decimal> timeLen { get; set; }
        public Nullable<System.DateTime> timeBegin { get; set; }
        public Nullable<System.DateTime> timeEnd { get; set; }
    }
}
